### ISSUE TITLE
HTTPoison error Fatal - Unknown CA. 

### ISSUE THREAD

**Issue by romariolopezc** [danielberkompas/ex_twilio#151]
```
2021-04-08T21:16:52.773335+00:00 app[web.1]: 21:16:52.772 [info] TLS :client: In state :certify at ssl_handshake.erl:1895 generated CLIENT ALERT: Fatal - Unknown CA
2021-04-08T21:16:52.773337+00:00 app[web.1]:
2021-04-08T21:16:52.774271+00:00 app[web.1]: 21:16:52.773 [error] Task #PID<0.4109.0> started from #PID<0.4108.0> terminating
2021-04-08T21:16:52.774274+00:00 app[web.1]: ** (HTTPoison.Error) {:tls_alert, {:unknown_ca, 'TLS client: In state certify at ssl_handshake.erl:1895 generated CLIENT ALERT: Fatal - Unknown CA\n'}}
2021-04-08T21:16:52.774274+00:00 app[web.1]: (ex_twilio 0.8.2) lib/ex_twilio/api.ex:19: ExTwilio.Api.request!/5
2021-04-08T21:16:52.774275+00:00 app[web.1]: (ex_twilio 0.8.2) lib/ex_twilio/api.ex:72: ExTwilio.Api.create/3
```

Seems that has to do something with twilio and not setting a connection

**Comment by romariolopezc** [comment]
This seems to happen only in my CI and PROD environment, locally it works :thinking:

**Comment by romariolopezc** [comment]
Fo anyone else having this problem: https://github.com/certifi/erlang-certifi/issues/46

I fixed it by doing: `mix deps.update certifi`
