### ISSUE TITLE
Lack of domain when running ExTwilio.Call.all()

### ISSUE THREAD

**Issue by erickhsiao** [danielberkompas/ex_twilio#38]
when you run ExTwilio.Call.all() to look up all previous calls, it went error due to lack of domain, the error message : 

`(HTTPotion.HTTPError) {:EXIT, {:badarg, {:gen_server, :call, [#PID<0.401.0>, {:send_req, {{:url, 'http:///2010-04-01/Accounts/xxxxx/Calls.json?PageSize=50&Page=1&PageToken=xxxxx', [], 80, :undefined, :undefined, '/2010-04-01/Accounts/xxxxx/Calls.json?PageSize=50&Page=1&PageToken=xxxxx', :http, :hostname}, [{'Content-Type', 'application/x-www-form-urlencoded; charset=UTF-8'}], :get, "", [basic_auth: {'xxxxx', 'xxxx'}], 5000}}, 5000]}}}`

if I add domain with that {:url} address, everything works.

**Comment by danielberkompas** [comment]
Did you set up your configuration as described in the README?

https://github.com/danielberkompas/ex_twilio#configuration

**Comment by erickhsiao** [comment]
yes, that all set, even api_domain, voice_application_sid
it works fine in Call.create,  but failed on Call.all

**Comment by rlb3** [comment]
I'm seeing the same thing with messages:

```elixir
ExTwilio.Message.all
```

```
** (HTTPotion.HTTPError) {:EXIT, {:badarg, {:gen_server, :call, [#PID<0.423.0>, {:send_req, {{:url, 'http:///2010-04-01/Accounts/xxxxx/Messages.json?PageSize=50&Page=1&PageToken=PASM177e4ff67cd24c5a8d1e134c11b3fc85', [], 80, :undefined, :undefined, '/2010-04-01/Accounts/xxxxx/Messages.json?PageSize=50&Page=1&PageToken=PASM177e4ff67cd24c5a8d1e134c11b3fc85', :http, :hostname}, [{'Content-Type', 'application/x-www-form-urlencoded; charset=UTF-8'}], :get, "", [basic_auth: {'xxxxx', 'xxxxx'}], 5000}}, 5000]}}}
[error] GenServer #PID<0.423.0> terminating
** (ArgumentError) argument error
    (kernel) gen_tcp.erl:149: :gen_tcp.connect/4
    (ibrowse) src/ibrowse_http_client.erl:758: :ibrowse_http_client.send_req_1/8
    (stdlib) gen_server.erl:629: :gen_server.try_handle_call/4
    (stdlib) gen_server.erl:661: :gen_server.handle_msg/5
    (stdlib) proc_lib.erl:240: :proc_lib.init_p_do_apply/3
Last message: {:send_req, {{:url, 'http:///2010-04-01/Accounts/xxxxx/Messages.json?PageSize=50&Page=1&PageToken=PASM177e4ff67cd24c5a8d1e134c11b3fc85', [], 80, :undefined, :undefined, '/2010-04-01/Accounts/xxxxx/Messages.json?PageSize=50&Page=1&PageToken=PASM177e4ff67cd24c5a8d1e134c11b3fc85', :http, :hostname}, [{'Content-Type', 'application/x-www-form-urlencoded; charset=UTF-8'}], :get, "", [basic_auth: {'xxxxx', 'xxxxx'}], 5000}}
State: {:state, [], 80, :undefined, #Reference<0.0.6.287>, false, :undefined, [], false, :undefined, false, [], {[], []}, :undefined, :idle, :undefined, "", 0, 0, [], :undefined, :undefined, :undefined, :undefined, false, :undefined, :undefined, "", :undefined, false, 213044, 0, :undefined, :undefined}
    (ex_twilio) lib/ex_twilio/api.ex:19: ExTwilio.Api.handle_response/1
    (ex_twilio) lib/ex_twilio/result_stream.ex:44: ExTwilio.ResultStream.fetch_page/2
    (ex_twilio) lib/ex_twilio/result_stream.ex:57: ExTwilio.ResultStream.process_page/1
       (elixir) lib/stream.ex:1099: Stream.do_resource/5
       (elixir) lib/enum.ex:1486: Enum.reduce/3
       (elixir) lib/enum.ex:2248: Enum.to_list/1
       (elixir) lib/enum.ex:961: Enum.into/2
```

But if I use `stream/0`

```elixir
ExTwilio.Message.stream |> Enum.take(1)
```

```
[%ExTwilio.Message{account_sid: "xxxxx",
  api_version: "2010-04-01",
  body: "Sent from your Twilio trial account - testing from elixir",
  date_created: "Thu, 26 May 2016 17:28:44 +0000",
  date_sent: "Thu, 26 May 2016 17:28:44 +0000",
  date_updated: "Thu, 26 May 2016 17:28:44 +0000", direction: "outbound-api",
  error_code: nil, error_message: nil, from: "+xxxxx", num_media: "0",
  num_segments: "1", price: "-0.00750", price_unit: "USD",
  sid: "SM5c7d0a175db24de38591f2e540edf21c", status: "delivered",
  subresource_uri: nil, to: "+xxxxx",
  uri: "/2010-04-01/Accounts/xxxxx/Messages/SM5c7d0a175db24de38591f2e540edf21c.json"}]

```

**Comment by rlb3** [comment]
A bit more information.

I have 50 messages I can list. If I do `ExTwilio.Message.stream |> Enum.take(51)` I get the same error. In fact, any number above 50 will get the error. The same error happens with `ExTwilio.Message.stream |> Enum.into([])` which is what `ExTwilio.Resource.all` does.
