### ISSUE TITLE
problem with lib

### ISSUE THREAD

**Issue by alec-c4** [danielberkompas/ex_twilio#52]
Hi, 
I have following error with poison 2.2.0 :(

```
iex(1)> use Mix.Config
#PID<0.282.0>
iex(2)> config :ex_twilio, account_sid: "sid", auth_token: "token"
:ok
iex(3)> calls = ExTwilio.Call.all
** (HTTPoison.Error) {:noproc, {:gen_server, :call, [:hackney_manager, {:new_request, #PID<0.278.0>, #Reference<0.0.7.981>, {:client, :undefined, {:metrics_ng, :metrics_dummy}, :hackney_ssl_transport, 'api.twilio.com', 443, "api.twilio.com", [], nil, nil, nil, true, :hackney_pool, 5000, false, 5, false, 5, nil, nil, nil, :undefined, :start, nil, :normal, false, false, false, :undefined, false, nil, :waiting, nil, 4096, "", [], :undefined, nil, nil, nil, nil, :undefined, ...}}, :infinity]}}
             lib/ex_twilio/api.ex:19: ExTwilio.Api.request!/5
             lib/ex_twilio/result_stream.ex:45: ExTwilio.ResultStream.fetch_page/2
    (elixir) lib/stream.ex:1121: anonymous fn/5 in Stream.resource/3
    (elixir) lib/enum.ex:1636: Enum.reduce/3
    (elixir) lib/enum.ex:2346: Enum.to_list/1
    (elixir) lib/enum.ex:1057: Enum.into/2
```

**Comment by danielberkompas** [comment]
What do you get if you run this?

```
iex> use Mix.Config
iex> config :ex_twilio, account_sid: "sid", auth_token: "token"
iex> Application.get_env(:ex_twilio)
```

I think the problem is most likely the fact that you are using `config` inside of IEX rather than in a `config.exs` file.

**Comment by alec-c4** [comment]
```
iex(1)> use Mix.Config
#PID<0.610.0>
iex(2)> config :ex_twilio, account_sid: "sid", auth_token: "token"
:ok
iex(3)> Application.get_env(:ex_twilio)
** (UndefinedFunctionError) function Application.get_env/1 is undefined or private. Did you mean one of:

      * get_env/2
      * get_env/3

    (elixir) Application.get_env(:ex_twilio)
iex(3)>
```

**Comment by alec-c4** [comment]
```
iex(3)> config :ex_twilio, ExTwilio, account_sid: "sid", auth_token: "token"
:ok
```

**Comment by alec-c4** [comment]
now, I've registered my Sid and token, but to attempt to retrieve sms list or send sms - I see following errors:

```
iex(7)> msg = ExTwilio.Message.create(from: "+79268891632", to: "+79268891632", body: "ExTwilio test")
{:error, "The requested resource /2010-04-01/Messages.json was not found", 404}
```

and 

```
iex(8)> ExTwilio.Message.all                                                             
** (MatchError) no match of right hand side value: {:error, "The requested resource /2010-04-01/Messages.json was not found", 404}
    (ex_twilio) lib/ex_twilio/result_stream.ex:46: ExTwilio.ResultStream.fetch_page/2
       (elixir) lib/stream.ex:1121: anonymous fn/5 in Stream.resource/3
       (elixir) lib/enum.ex:1636: Enum.reduce/3
       (elixir) lib/enum.ex:2346: Enum.to_list/1
       (elixir) lib/enum.ex:1057: Enum.into/2
```

**Comment by danielberkompas** [comment]
See this previous bug report. https://github.com/danielberkompas/ex_twilio/issues/33
